package com.pojos;
// Generated 05.Eyl.2018 13:22:28 by Hibernate Tools 4.3.1



/**
 * Akademisyenders generated by hbm2java
 */
public class Akademisyenders  implements java.io.Serializable {


     private Integer id;
     private String tc;
     private String dersid;

    public Akademisyenders() {
    }

    public Akademisyenders(String tc, String dersid) {
       this.tc = tc;
       this.dersid = dersid;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTc() {
        return this.tc;
    }
    
    public void setTc(String tc) {
        this.tc = tc;
    }
    public String getDersid() {
        return this.dersid;
    }
    
    public void setDersid(String dersid) {
        this.dersid = dersid;
    }




}


