package com.pojos;
// Generated 05.Eyl.2018 13:22:28 by Hibernate Tools 4.3.1



/**
 * Bolum generated by hbm2java
 */
public class Bolum  implements java.io.Serializable {


     private String bolumid;
     private String bolumadi;

    public Bolum() {
    }

    public Bolum(String bolumid, String bolumadi) {
       this.bolumid = bolumid;
       this.bolumadi = bolumadi;
    }
   
    public String getBolumid() {
        return this.bolumid;
    }
    
    public void setBolumid(String bolumid) {
        this.bolumid = bolumid;
    }
    public String getBolumadi() {
        return this.bolumadi;
    }
    
    public void setBolumadi(String bolumadi) {
        this.bolumadi = bolumadi;
    }




}


