package com.pojos;
// Generated 05.Eyl.2018 13:22:28 by Hibernate Tools 4.3.1



/**
 * Ders generated by hbm2java
 */
public class Ders  implements java.io.Serializable {


     private String dersid;
     private String dersadi;
     private String bolumid;
     private String akademisyentc;
     private int donem;

    public Ders() {
    }

    public Ders(String dersid, String dersadi, String bolumid, String akademisyentc, int donem) {
       this.dersid = dersid;
       this.dersadi = dersadi;
       this.bolumid = bolumid;
       this.akademisyentc = akademisyentc;
       this.donem = donem;
    }
   
    public String getDersid() {
        return this.dersid;
    }
    
    public void setDersid(String dersid) {
        this.dersid = dersid;
    }
    public String getDersadi() {
        return this.dersadi;
    }
    
    public void setDersadi(String dersadi) {
        this.dersadi = dersadi;
    }
    public String getBolumid() {
        return this.bolumid;
    }
    
    public void setBolumid(String bolumid) {
        this.bolumid = bolumid;
    }
    public String getAkademisyentc() {
        return this.akademisyentc;
    }
    
    public void setAkademisyentc(String akademisyentc) {
        this.akademisyentc = akademisyentc;
    }
    public int getDonem() {
        return this.donem;
    }
    
    public void setDonem(int donem) {
        this.donem = donem;
    }




}


