package com.pojos;
// Generated 05.Eyl.2018 13:22:28 by Hibernate Tools 4.3.1



/**
 * Ogrenciisleri generated by hbm2java
 */
public class Ogrenciisleri  implements java.io.Serializable {


     private String tc;
     private String ad;
     private String soyad;
     private String sifre;
     private String email;
     private String adres;
     private String yas;

    public Ogrenciisleri() {
    }

    public Ogrenciisleri(String tc, String ad, String soyad, String sifre, String email, String adres, String yas) {
       this.tc = tc;
       this.ad = ad;
       this.soyad = soyad;
       this.sifre = sifre;
       this.email = email;
       this.adres = adres;
       this.yas = yas;
    }
   
    public String getTc() {
        return this.tc;
    }
    
    public void setTc(String tc) {
        this.tc = tc;
    }
    public String getAd() {
        return this.ad;
    }
    
    public void setAd(String ad) {
        this.ad = ad;
    }
    public String getSoyad() {
        return this.soyad;
    }
    
    public void setSoyad(String soyad) {
        this.soyad = soyad;
    }
    public String getSifre() {
        return this.sifre;
    }
    
    public void setSifre(String sifre) {
        this.sifre = sifre;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAdres() {
        return this.adres;
    }
    
    public void setAdres(String adres) {
        this.adres = adres;
    }
    public String getYas() {
        return this.yas;
    }
    
    public void setYas(String yas) {
        this.yas = yas;
    }




}


