package com.pojos;
// Generated 05.Eyl.2018 13:22:28 by Hibernate Tools 4.3.1



/**
 * Ogrenciders generated by hbm2java
 */
public class Ogrenciders  implements java.io.Serializable {


     private Integer id;
     private String tc;
     private String dersid;
     private Integer vize;
     private Integer final_;
     private Integer but;

    public Ogrenciders() {
    }

	
    public Ogrenciders(String tc, String dersid) {
        this.tc = tc;
        this.dersid = dersid;
    }
    public Ogrenciders(String tc, String dersid, Integer vize, Integer final_, Integer but) {
       this.tc = tc;
       this.dersid = dersid;
       this.vize = vize;
       this.final_ = final_;
       this.but = but;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTc() {
        return this.tc;
    }
    
    public void setTc(String tc) {
        this.tc = tc;
    }
    public String getDersid() {
        return this.dersid;
    }
    
    public void setDersid(String dersid) {
        this.dersid = dersid;
    }
    public Integer getVize() {
        return this.vize;
    }
    
    public void setVize(Integer vize) {
        this.vize = vize;
    }
    public Integer getFinal_() {
        return this.final_;
    }
    
    public void setFinal_(Integer final_) {
        this.final_ = final_;
    }
    public Integer getBut() {
        return this.but;
    }
    
    public void setBut(Integer but) {
        this.but = but;
    }




}


